name: google

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
